name: BriefCakes
favicon: null
layout_spectrum: 0.2499960872810334
typography_spectrum: 0.6002
title: Brief Cakes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070803'
    - '#e9ecdb'
    - '#9b7740'
    - '#a3e658'
    - '#ff90ac'
  brandStrength: 0.25
  lightness: 0.3261911100707948
  saturation: 0.2627441755030304
  rhythmicContrast: 0.8391851887572557
purpose: []
