name: BriefCakes
favicon: null
layout_spectrum: 0.2499960872810334
typography_spectrum: 0.9636645193677396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.25510989082977176
  lightness: 0.3261911100707948
  saturation: 0.2627441755030304
  rhythmicContrast: 0.8391851887572557
purpose: []
